[package]
name = "web-glitz"
version = "0.1.0"
authors = ["Roland Schermer <roland0507@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
fnv = "1.0.3"
futures = "0.1.25"
js-sys = "0.3.10"
serde = "1.0"
serde_derive = "1.0"
proc-macro-hack = "0.5"
web-glitz-macros = { version = "0.1.0", path = "../web_glitz_macros" }

[dependencies.wasm-bindgen]
version = "0.2.33"
features = ["serde-serialize"]

[dependencies.web-sys]
version = "0.3.10"
features = [
    "HtmlCanvasElement",
    "WebGl2RenderingContext",
    "WebGlActiveInfo",
    "WebGlBuffer",
    "WebGlFramebuffer",
    "WebGlProgram",
    "WebGlRenderbuffer",
    "WebGlSampler",
    "WebGlShader",
    "WebGlSync",
    "WebGlTexture",
    "WebGlUniformLocation",
    "WebGlVertexArrayObject",
    "Window",
    "console"
]
