[package]
name = "web-glitz"
version = "0.1.0"
authors = ["Roland Schermer <roland0507@gmail.com>"]

[dependencies]
failure = "0.1.3"
futures = "0.1.25"
wasm-bindgen = "0.2.23"
web-glitz-derive = { version = "0.1.0", path = "../web_glitz_derive" }

[dependencies.web-sys]
version = "0.3.0"
features = [
    "WebGl2RenderingContext",
    "WebGlBuffer",
    "WebGlFramebuffer",
    "WebGlProgram",
    "WebGlRenderbuffer",
    "WebGlSampler",
    "WebGlSync",
    "WebGlTexture",
    "WebGlVertexArrayObject",
    "Window"
]
