[package]
name = "web-glitz"
version = "0.1.0"
authors = ["Roland Schermer <roland0507@gmail.com>"]

[dependencies]
failure = "0.1.3"
fnv = "1.0.3"
futures = "0.1.25"
js-sys = { git = "https://github.com/rustwasm/wasm-bindgen" }
proc-macro-hack = "0.5"
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }
web-glitz-derive = { version = "0.1.0", path = "../web_glitz_derive" }

[dependencies.web-sys]
git = "https://github.com/rustwasm/wasm-bindgen"
features = [
    "WebGl2RenderingContext",
    "WebGlActiveInfo",
    "WebGlBuffer",
    "WebGlFramebuffer",
    "WebGlProgram",
    "WebGlRenderbuffer",
    "WebGlSampler",
    "WebGlShader",
    "WebGlSync",
    "WebGlTexture",
    "WebGlUniformLocation",
    "WebGlVertexArrayObject",
    "Window"
]
