[package]
name = "web-glitz"
version = "0.1.0"
description = "Rusty low-level web-graphics library on top of WebGL 2.0."
authors = ["Roland Schermer <roland0507@gmail.com>"]
edition = "2018"
repository = "https://github.com/RSSchermer/weg_glitz.rs"
homepage = "https://github.com/RSSchermer/weg_glitz.rs"
license = "MIT"
readme = "../README.md"

[dependencies]
failure = "0.1.3"
fnv = "1.0.3"
futures-preview = { version = "=0.3.0-alpha.17", features = ["compat"] }
js-sys = "0.3.24"
serde = "1.0"
serde_derive = "1.0"
proc-macro-hack = "0.5"
web-glitz-macros = "0.1.0"

[dependencies.wasm-bindgen]
version = "0.2.48"
features = ["serde-serialize"]

[dependencies.web-sys]
version = "0.3.25"
features = [
    "CanvasRenderingContext2d",
    "HtmlCanvasElement",
    "HtmlImageElement",
    "ImageData",
    "WebGl2RenderingContext",
    "WebGlActiveInfo",
    "WebGlBuffer",
    "WebGlFramebuffer",
    "WebGlProgram",
    "WebGlRenderbuffer",
    "WebGlSampler",
    "WebGlShader",
    "WebGlSync",
    "WebGlTexture",
    "WebGlTransformFeedback",
    "WebGlUniformLocation",
    "WebGlVertexArrayObject",
    "Window",
    "console"
]

[dev-dependencies]
wasm-bindgen-futures = {version = "0.3.25", features = ["futures_0_3"] }
