[package]
name = "web-glitz-macros"
version = "0.1.0"
authors = ["Roland Schermer <roland0507@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
fnv = "1.0.3"
proc-macro2 = "0.4"
proc-macro-hack = "0.5"
quote = "0.6"
syn = "0.15"
